### ISSUE TITLE
Short term roadmap

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#1]
- [x] Increase logging support
- [x] Ensure comments provider are additive [(core)](https://github.com/Microsoft/vscode/issues/51622)
- [x] PR viewlet should how the union of all remotes (will have picker later on)
- [x] Ensure cross-platform support
- Architecture
   - [x] Ensure clear auth separation
   - [x] Ensure clear model separation
   - [x] Basic model tests
- [x] Setup CI
- [x] Multi-root folder support: Investigate how the active source control provider can control what's visible in the PR viewlets
- [x] Stabilization, bug fixes
- [x] OAuth authentication support
- [ ] Adopt Git extension API to support multi-root-folders
- [x] Improve PR overview page
- [x] Improve commenting support
- [ ] Improve section management in SCM view
- [x] Work with GH on supporting large diff hunks
- [x] Publish preview in Marketplace
----
- [ ] Investigate alternatives for multi-vendor story; i.e. support PR from providers other than GH

**Comment by rebornix** [comment]
Right now extensions can create SCM source control but there is no way to access current active source control instance. It would be great if we can access them like how to access active text editor, the API can be like


```js
    export namespace scm {
		export let activeSourceControl: SourceControl | undefined;
		export const onDidChangeActiveSourceControl: Event<SourceControl | undefined>;

		/**
		 * ~~The [input box](#SourceControlInputBox) for the last source control
		 * created by the extension.~~
		 *
		 * @deprecated Use SourceControl.inputBox instead
		 */
		export const inputBox: SourceControlInputBox;

		/**
		 * Creates a new [source control](#SourceControl) instance.
		 *
		 * @param id An `id` for the source control. Something short, eg: `git`.
		 * @param label A human-readable string for the source control. Eg: `Git`.
		 * @param rootUri An optional Uri of the root of the source control. Eg: `Uri.parse(workspaceRoot)`.
		 * @return An instance of [source control](#SourceControl).
		 */
		export function createSourceControl(id: string, label: string, rootUri?: Uri): SourceControl;
	}
```

**Comment by lostintangent** [comment]
@kieferrm @rebornix +1! Being able to retrieve the active SourceControl instance would be valuable for Live Share as well. I’d love to see this become possible 😁

**Comment by egamma** [comment]
//  @joaomoreno fyi

**Comment by ha404** [comment]
Awesome work guys! Can't wait to use this, been following it closely, gonna be a game changer in the productivity department for sure 😄
