### ISSUE TITLE
Plan for March 2019

### ISSUE THREAD

**Issue by meaghanlewis** [Microsoft/vscode-pull-request-github#1023]
- [x] :runner: Work with VS Code to review and adapt the comments provider API @rebornix 
- [ ] :runner: Move to a framework for the overview page #1096 @queerviolet 
- [ ] :runner: Loading Pull Request List via GraphQL: https://github.com/Microsoft/vscode-pull-request-github/pull/1022 @StanleyGoldman 
- [ ] :runner: Show PR review status in tree view #681 @StanleyGoldman 
- [ ] :runner: Add more metrics: https://github.com/Microsoft/vscode-pull-request-github/issues/1029 @annthurium
- [ ]  Support opening a pull request by number #266 
- [ ]  Explore displaying GitHub notifications in VS Code
 
Test plan issues:
https://github.com/Microsoft/vscode/issues/71103

**Comment by meaghanlewis** [comment]
Testing the week of 3/25
Release by 4/3
