### ISSUE TITLE
Plan for April 2019

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1109]
- [x] :runner: Move to a framework for the overview page #1096 @queerviolet 
- [ ] :runner: Loading Pull Request List via GraphQL: https://github.com/Microsoft/vscode-pull-request-github/pull/1022 @StanleyGoldman 
- [ ] :runner: Show PR review status in tree view #681 @StanleyGoldman 
- [x] :runner: Add more metrics: https://github.com/Microsoft/vscode-pull-request-github/issues/1029 @annthurium
- [ ] Polishing for commenting API @rebornix 
- [x]  Explore displaying GitHub notifications #1128  @meaghanlewis
- [ ] Explore offline slowness #1091 @queerviolet

**Comment by meaghanlewis** [comment]
Timeline:
Code freeze is May 6th
Testing week of May 13th
Release on May 16th

**Comment by meaghanlewis** [comment]
Test issue: https://github.com/microsoft/vscode-pull-request-github/issues/1152
