### ISSUE TITLE
Plan for May 2019

### ISSUE THREAD

**Issue by meaghanlewis** [microsoft/vscode-pull-request-github#1154]
For this sprint, the focus will be on enhancements and improvements to current functionality. Add items here that you would like to see improved this sprint.

## Ideas
@queerviolet 
- improvements on overview page. cleanup css.  (note: for colors we should try to stick to ones already in the theme)

@meaghanlewis 
- show PR status in tree view . #681 
- draft PRs #1129 
- making username in status bar interactive (manage accounts, navigate to PRs in tree view, etc.) related issue: #360 

@kuychaco 
- See a list of all my PRs
- improve UX for creating a PR so that description can be provided before publishing/notifying folks

@StanleyGoldman 
  - exploring the GHE experience and resolving issues
  - use graphql query for users to generate their own categories (+1 from @RMacfarlane) #1106

@smashwilson 
 - looking into adding test coverage. (idea from @queerviolet on adding tests to overview page)
 - reporting tests metadata in Azure pipelines

@rebornix 
- moving CI over to a shared account/organization 
- API finalization and improve performance for creating comment threads
- Find a way to clean up remotes 

@RMacfarlane 
- be able to delete a branch after merging pull request #310
- be able to assign PRs #1063 
- handle rebase workflow #802
------------------------------------------------
## What we've committed to:
- [ ] 🏃 @queerviolet Improvements overview
- [x] 🏃 @kuychaco Draft PRs #1129
- [x] 🏃 @smashwilson Expand test coverage #1169 
- [x] @RMacfarlane Allow custom pull request filters #1106 
- [x] 🏃 @RMacfarlane @rebornix Adoption of new comments API #1168 
- [x] @RMacfarlane  Avoid duplication of workspace file #1099

**Comment by cgarciae** [comment]
Delete branch after pull request would be awesome, still need to go to github for this.
