### ISSUE TITLE
GHPR: Iteration Plan for April 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#1619]
### General
- [x] Change extension icon to be the official GH PR icon https://github.com/microsoft/vscode-pull-request-github/issues/1617 @rmacfarlane
- [x] Adopt GH authentication https://github.com/microsoft/vscode-pull-request-github/issues/1616 @rmacfarlane

### @user #issue hovers/completions
- [x] :runner: Hovers for users with location data are too wide https://github.com/microsoft/vscode-pull-request-github/issues/1578 @octref @jrieken
- [ ] :runner: Improve the rendering of the GH hovers (user, issues) @alexr00 @jrieken
- [x] :runner: Support hovering over issue links that refer to comments #1506 @alexr00 

### Repositories
- [x] :runner: Contribute a GH repository picker to the Git: Clone command  #1547 @joaomoreno 
- [x] :runner: Support to export a git workspace to GH #1664 @joaomoreno 

### Issues support
- [x] :runner: Allow editing of issue details when creating issue from code action  https://github.com/microsoft/vscode-pull-request-github/issues/1608 @alexr00 
- [x] Issues view: Add variables in queries, e.g. ${currentRepository}  @alexr00 
- [x] :runner: Work on issue: Support to create a **draft** PR @alexr00 
- [ ] :muscle: Work on issue: Explore offering to create a fork when no commit rights @alexr00
