### ISSUE TITLE
GHPR: Iteration Plan for May 2020

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#1788]
### Repositories
- [x] Make clone from/publish to GitHub generally available @joaomoreno 
- [x] Complete Support to export code to GitHub #1664 @joaomoreno 
- [x] :runner: Add a remote GitHub repository https://github.com/microsoft/vscode/issues/98158 @joaomoreno 
- [x] :runner: Add interface to control what gets included in the repo https://github.com/microsoft/vscode/issues/98157 @joaomoreno 
- [ ] Offer to create fork on GH when no commit rights @joaomoreno 
- [ ] Create a new repository from a template @joaomoreno 

### Issues
- [ ] :muscle: Adopt generalized rich hover in the Issues view @alexr00 
- [x] :runner: Adopt support for richer hover for issues @alexr00 
- [x] :runner: Polish [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+assignee%3Aalexr00+milestone%3A%22May+2020%22)
- [ ] :muscle: Work on issue: Explore offering to create a fork when no commit rights @alexr00
