### ISSUE TITLE
Feedback on the improvements to the PR flow

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-pull-request-github#2372]
Refs: #2293

I just want to capture a bunch of my feedback here, and we can split this out into individual issues after.

## General
- [ ] Clicking `Create Pull Request` while in "focus view" opens the new views below the focus mode (would expect them on top) - [EA]
- [ ] Sometimes focus mode won't open (not sure why yet) [EA]

## SCM view
- [x] Use PR icon in SCM view header, rather than the +
- [ ] Add a `Pull Request` submenu under the SCM overflow menu (Below Pull), with options for `Create...` and `Create Draft...` (or maybe called `New...` and `New Draft...`) [EA]

## Create PR View
- Add a "source" repository selector (when there is more than 1 repo)
- Add a "source" branch selector, rather than always the current branch

## PR Focus "status" view
- [x] ~Suggest changing the title to be `PR #<number>` or `Pull Request #<number>` and then use the description to be the title of the PR [RM] https://github.com/microsoft/vscode-pull-request-github/issues/2459~
- [x] Should have a refresh button to update the view with the latest PR info [RM] https://github.com/microsoft/vscode-pull-request-github/issues/2455
- Should show review status, if you are a reviewer -- probably also a "start review" button?
- [x] Should have a "details" button or something to open the details webview [RM] https://github.com/microsoft/vscode-pull-request-github/issues/2456
- [ ] Change `Delete Branch` to be `Clean Up...` [RM] https://github.com/microsoft/vscode-pull-request-github/issues/2460
- [ ] Add a _Close Pull Request..._ button with a confirmation [RM]
- [ ] Add a new button to switch back to the "main" branch -- `Switch back to 'main'` or something like that [RM]
- Add the _Clean Up..._ button here -- when you just want to get rid of the PR and back to the main

## PR Focus "changes" view
- [x] Suggest changing the title to be `Changes in PR #<number>` or `Changes in Pull Request #<number>` and then use the description to be the title of the PR
- [ ] Could lose the root node, and maybe just have a `Commits` node at the top, and then all the directly files below it to simplify things [EA]

## "Clean Up" quick pick
- [ ] Add options to suspend or delete the Codespace [RM]
- Wish we could have disabled (uncheckable) quick pick items -- because it would be nice on the clean up quick pick to say why its not offering to delete the remote (because its in use by another branch)

**Comment by alexr00** [comment]
Most of these have since been addressed.
