### ISSUE TITLE
Plan for June 2021

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-pull-request-github#2775]
### UX
- [x] Improve appearance of the PR overview page [2648](https://github.com/microsoft/vscode-pull-request-github/issues/2648) @misolori @alexr00

### Fundamentals
- [x] Accessibility improvements [2737](https://github.com/microsoft/vscode-pull-request-github/issues/2737) @alexr00
- [ ] Investigate performance issues/improvements for branch PR detection [2487](https://github.com/microsoft/vscode-pull-request-github/issues/2487) @eamodio
- [ ] :runner: Improve support for virtual workspaces [2722](https://github.com/microsoft/vscode-pull-request-github/issues/2722) @alexr00
- [x] Issues [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22June+2021%22) @alexr00

### Engineering
- [x] Automated copyright/governance support @alexr00
- [ ] :runner: Investigate into automated web test @alexr00 @aeschli
