### ISSUE TITLE
GHPRI: Iteration Plan for July 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-pull-request-github#2833]
This plan captures our work in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/128444). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Fundamentals
- [ ] Investigate performance issues/improvements for branch PR detection [vscode-pull-request-github#2487](https://github.com/microsoft/vscode-pull-request-github/issues/2487) @eamodio
- [x] Improve support for virtual workspaces [vscode-pull-request-github#2722](https://github.com/microsoft/vscode-pull-request-github/issues/2722) @alexr00
- [x] :runner: Issues [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22July+2021%22) @alexr00

### Features
- [x] Support to start working on an issue in another repository [vscode-pull-request-github#2820](https://github.com/microsoft/vscode-pull-request-github/issues/2820) @alexr00

### Engineering
- [x] Investigate into automated web test [vscode-pull-request-github#2845](https://github.com/microsoft/vscode-pull-request-github/issues/2845) @alexr00 @aeschli
- [x] Run automated web tests as part of the CI build [vscode-pull-request-github#2845](https://github.com/microsoft/vscode-pull-request-github/issues/2845) @alexr00 @aeschli
