### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Angie20182** [microsoft/vscode-pull-request-github#5296]
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5190
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5239
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5216
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5246
```
