### ISSUE TITLE
H

### ISSUE THREAD

**Issue by Angie20182** [microsoft/vscode-pull-request-github#5324]
- Extension version:
- VSCode Version:
- OS:

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5323
- [ ] https://github.com/microsoft/vscode-pull-request-github/pull/5322
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/2639
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5321
```
