### ISSUE TITLE
Plan for October 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#544]
## Plan Items 
- [x] Support for merging PRs
- [x] Support for multi-root workspaces @RMacfarlane 
- [ ] :runner: Create PR (after create PR, the workspace turns immediately into a review workspace) #554 #620 @queerviolet @rebornix
- [x] :runner: Support editing/removing comments #107 #643 @RMacfarlane 

### Bugs
- [x] HTML sanitization @rebornix 
- [x] Improve SSH/HTTPS remote management @rebornix 
- [x] Stabilizing / bug fixing: [query](https://github.com/Microsoft/vscode-pull-request-github/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Abug+milestone%3A%22October+2018%22)
- [x] Check out PR merges into current working branch #594 @rebornix 

### Engineering
- [x] Reduce bundle size by using git extension @rebornix 

### Performance
- Use caching to improve loading times and retaining of state 
   - [ ] :runner: overview page
   - [x] comments in the text and diff editors @rebornix

---
### Deferred Items
- [ ] Caching state/data of tree views
- [ ] :runner: Allow to group comments into a review @queerviolet
- [ ] :muscle: Investigate which call optimizations we can make when moving to GH API v4
- [ ] :muscle: Do we need a JS framework (React or Vue) for the overview page?
- [ ] :muscle: Show compliance status on overview page
- [ ] :muscle: Support for submodules
- [ ] Add client-side logging of GH requests to look for call optimizations

---
### Dependencies on VS Code core
- modifying/deleting comments API https://github.com/Microsoft/vscode/issues/58078
- improve section management for contributions
- polish visual presentation of commentable range and actually changed lines
- keybindings for the comments panel (show, focus)
