### ISSUE TITLE
vulnerability

### ISSUE THREAD

**Issue by bamayosse** [microsoft/vscode-pull-request-github#5464]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/pull/5469
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/3451
- [ ] https://github.com/microsoft/vscode-pull-request-github/pull/5465
```

**Comment by alexr00** [comment]
I don't understand the screen shot. Can you please elaborate?
