### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by behnamkhanioffical** [microsoft/vscode-pull-request-github#5529]
- Extension version:
- VSCode Version:
- OS:
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5453
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5528
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5517
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5523
```

**Comment by behnamkhanioffical** [comment]
@behnamkhanioffical 
#5471 
#5453 
#5406 
#5430
