### ISSUE TITLE
Parche

### ISSUE THREAD

**Issue by WilmarE** [microsoft/vscode-pull-request-github#5778]
- Extension version:
- VSCode Version:
- OS:
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5661
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5771
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5326
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5756
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5705
- [ ] https://github.com/microsoft/vscode-pull-request-github/pull/5777
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5776
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/5576
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/4761
```
