### ISSUE TITLE
CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Julytampos** [microsoft/vscode-pull-request-github#6098]
- Extension version:
- VSCode Version:
- OS:
- Repository Clone Configuration (single repository/fork of an upstream repository):
- Github Product (Github.com/Github Enterprise version x.x.x):

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/6096
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/6081
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/2103
- [ ] https://github.com/microsoft/vscode-pull-request-github/issues/6090
```

```[tasklist]
### Tasks
```
