### ISSUE TITLE
TODO for notifications view

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode-pull-request-github#6292]
- [x] Add action to mark item as being read from a tree view : https://github.com/microsoft/vscode-pull-request-github/pull/6298
- [x] Explore opening the quick chat instead of the panel chat instead https://github.com/microsoft/vscode-pull-request-github/pull/6315
  - [x] Add a setting to toggle what kind of view is used to summarize from the notifications view if we decide to use the quick chat
- [x] Add support for clicking on the notification tree which summarizes the issue too https://github.com/microsoft/vscode-pull-request-github/pull/6301
- [x] Add action inside of the panel chat for making a notification as being read https://github.com/microsoft/vscode-pull-request-github/pull/6305
- [x] Rewrite the prompt so that closed issues and notifications are not pushed to the bottom, but are given a lower score. https://github.com/microsoft/vscode-pull-request-github/pull/6309
- [ ] Add in the menu an action which allows us to filter and show the notifications related to only issues, only PRs, only closed, only open etc.
  - [ ] To this effect, check if there is API in order to show only these relevant issues, or do we have to fetch everything and then filter down?
  - [ ] Modify the menu to have a submenu, Sort By and Filter By
- [ ] Investigate why createdAt on comments is null and why lastReadAt is null to on thread

cc @lszomoru @alexr00

**Comment by alexr00** [comment]
> Add action to mark item as being read from a tree view

I am not sure if it makes sense, but the tree does have the option to add a checkbox. However, maybe it is weird to have a tree item that deletes itself from the tree when checked.

**Comment by aiday-mar** [comment]
True, that could be a bit weird. So perhaps I will instead add an icon that triggers a mark as read command.

**Comment by aiday-mar** [comment]
Most of these items have been addressed, so closing this. Feel free to comment here if there is anything that needs to be done.
