### ISSUE TITLE
Plan for November 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#678]
## Plan Items
- [x] create PR @rebornix @queerviolet 
- [x] Support for suggest comments @rmacfarlane
- [x] Investigate frequent re-login requests (expires too fast, no refresh?) #680 @rebornix 
- [ ] :runner: Windows performance issue #612 @rebornix
- [x] Add client-side logging of GH requests to look for call optimizations @rebornix 
- [ ] :runner: grouping comments into a review
- [x] edit PR title @rmacfarlane
- [x] Publish daily insider version of the extension through CI @rebornix @rmacfarlane

### Pain points / Missing functionality 
- [ ] intellisense for @mentions and issue numbers @rebornix
   - [ ] incremental API V4 adoption
- [ ] resolve a conversation @rebornix
- [ ] flow for resolving conflicts @rebornix
- [ ] delete branch after merging PR https://github.com/Microsoft/vscode-pull-request-github/issues/350 @rebornix
- [ ] :hand: can't add images @rmacfarlane
- [ ] can't choose options how to merge @rmacfarlane
- [ ] allow me to keep track of which files I reviewed @RMacfarlane

**Comment by rebornix** [comment]
> IntelliSense for @mentions and issue numbers

The same api can work for assigning reviewers and assignees, right now after I created a PR, I have to come back the website for that.

**Comment by rebornix** [comment]
Authentication issue we are running into now https://github.com/Microsoft/vscode/issues/60773 .
