### ISSUE TITLE
Plan for January 2019

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#762]
## Plan Items

- [x] Windows performance issue #612 @rebornix
- [x] incremental API V4 adoption
### Tree View

- [x] Diff from fork point state to current file state https://github.com/Microsoft/vscode-pull-request-github/issues/288

### Description/Overview

- [x] allow to reload overview page @RMacfarlane 
- Status Check / Merge @RMacfarlane 
   - [x] Status check should cover "mergeability" https://github.com/Microsoft/vscode-pull-request-github/issues/725
   - [x] Squash or Rebase Merge PR https://github.com/Microsoft/vscode-pull-request-github/issues/593
- Timeline Events @rebornix 
   - [x] https://github.com/Microsoft/vscode-pull-request-github/pull/831
     - [x] Indicate when a PR has been merged on the description page https://github.com/Microsoft/vscode-pull-request-github/issues/617
     - [x] PR approvals aren't very obvious https://github.com/Microsoft/vscode-pull-request-github/issues/303
     - [x] Linkify issue references https://github.com/Microsoft/vscode-pull-request-github/issues/566
 - [ ]  :runner: :muscle: Add reviewers within the description panel of PR https://github.com/Microsoft/vscode-pull-request-github/issues/412

### Workflow

- [x] grouping comments into a review @queerviolet @RMacfarlane
- [ ] :runner: Comments do not show reactions https://github.com/Microsoft/vscode-pull-request-github/issues/46
   

-----

### Deferred
- Support opening a pull request by number https://github.com/Microsoft/vscode-pull-request-github/issues/266
 - Pull request description code block syntax highlighting https://github.com/Microsoft/vscode-pull-request-github/issues/490
- Show PR review status https://github.com/Microsoft/vscode-pull-request-github/issues/681

-----

### Pain points / Missing functionality 
- [ ] intellisense for @mentions and issue numbers @rebornix
- [ ] resolve a conversation @rebornix
- [ ] flow for resolving conflicts @rebornix
- [ ] delete branch after merging PR https://github.com/Microsoft/vscode-pull-request-github/issues/350 @rebornix
- [ ] can't choose options how to merge @rmacfarlane
- [ ] allow me to keep track of which files I reviewed @RMacfarlane 
- [ ] :hand: can't add images @rmacfarlane
