### ISSUE TITLE
Plan for February 2019

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-pull-request-github#921]
- [x] Add reviewers within the description panel of PR #412 @RMacfarlane @rebornix @misolori 
- [x] Comments do not show reactions #46 @rebornix 
- [ ] :runner: Explore consolidating the two tree views into one: annotated checked out PR https://github.com/Microsoft/vscode-pull-request-github/pull/966 @RMacfarlane 
- [x] Explore setting to move consolidated tree view to activity bar  https://github.com/Microsoft/vscode-pull-request-github/issues/976 @RMacfarlane 
- [ ]  :runner: Work with VS Code to review and adapt the comments provider API @rebornix 
- [ ] :runner: Move to a framework for the overview page @queerviolet 
---
-  [ ] :muscle: Show PR review status in tree view #681
- [ ] :muscle: Support opening a pull request by number #266

Test items:
https://github.com/Microsoft/vscode/issues/69255
https://github.com/Microsoft/vscode/issues/69254
https://github.com/Microsoft/vscode/issues/69255

**Comment by Astrantia** [comment]
@rebornix explore removing the Description button and view overview page directly when clicking the PR title?

**Comment by rebornix** [comment]
@Astrantia thanks for the feedback, it's a valid one and we can explore that when we explore merging two tree views.

**Comment by Astrantia** [comment]
@rebornix No problem. I also noticed that extension still needed to be reloaded in vscode 1.31. Does this mean you haven't tweaked it for 1.31? Go extension didn't need a reload.
